### PR TITLE
Update prometheus to 2.16.0

### PR DESCRIPTION
**Pull request by roidelapluie**
I have also created
https://github.com/cloudalchemy/ansible-prometheus/pull/267

But I think we can keep the version explicit here, it will quickly
enable us to update to release candidates, instead of playing the game
of adding/removing lines each time.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by SuperQ** [comment]
Let's remove the version pinning, as we normally keep the site up-to-date in the upstream role. There are auto-deployment bots running to keep things up to date.

**Comment by SuperQ** [comment]
IMO, we should not be running the demo site on RCs. Let's just keep it automated on latest stable.

**Comment by roidelapluie** [comment]
On 16 Feb 08:39, Ben Kochie wrote:
> IMO, we should not be running the demo site on RCs. Let's just keep it automated on latest stable.

I won't block on this but I think it is nice to demo the RCs.

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by RichiH** [comment]
I would argue that we need a permanently known-good demo.

That being said, there's no reason not to have a site for RC demos in
parallel while we have them.

**Comment by roidelapluie** [comment]
I have un-pinned the version

**Comment by paulfantom** [comment]
> That being said, there's no reason not to have a site for RC demos in
parallel while we have them.

If needed, we can deploy both from one repo. To do this we just need another inventory file and move few vars there, like in https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout 

Do we want it though?

**Pull request merged**
