### PR TITLE
Bringing in latest version of a demo site

### PR DESCRIPTION
**Pull request by paulfantom**
Demo site for cloudalchemy.org worked fine since quite some time, but I will be stopping hosting that site in February 2020. It would be nice if prometheus org would pick it up.

This PR is bringing all changes that happened basically since forking repo here. All changes are adjusted to prometheus organization.

What was done:
- all influxdb references were removed
- all uptimerobot references were removed
- `demo.cloudalchemy.org` was changed into `demo.prometheus.io` in places where that change wasn't present before
- one instance of random_exporter was added (as requested in #3)
- deployment script/wrapper was added
- docker is no longer installed
- prometheus storage retention was changed to 14d
- added subdomains for all exporters to allow encrypted communication with them

The last point is kind of a workaround of an issue we had with some browsers (more in https://github.com/cloudalchemy/demo-site/issues/13). This would need to setup following subdomains (assuming demo site is hosted at `demo.prometheus.io`:
- prometheus.demo.prometheus.io
- grafana.demo.prometheus.io
- alertmanager.demo.prometheus.io
- node.demo.prometheus.io
- snmp.demo.prometheus.io
- blackbox.demo.prometheus.io

Such setup allows to access every component via HTTP and HTTPS. For example prometheus would be available at http://demo.prometheus.io:9090 and at https://prometheus.demo.prometheus.io

/cc @RichiH @SuperQ

### CODE REVIEW

**Comment by SuperQ** [comment]
Sorry, this came in the first day of CCC Camp, so it completely fell off my radar.

Yes, we should very much move things to the official Prometheus demo site.

**Comment by paulfantom** [comment]
DCO check is failing because I am including changes from over a year of development in a separate repository, where signing commits wasn't necessary. Any advice on how to proceed with this issue?

**Comment by paulfantom** [comment]
One thing that wasn't mentioned before: after the migration is complete I would like to set up a temporary redirect from `*.demo.cloudalchemy.org` to respective domains in `demo.prometheus.io` :)

**Comment by SuperQ** [comment]
If you say it's ok, what I can do is add a DCO signoff and do a squash commit.

Then I can override the DCO check

**Comment by paulfantom** [comment]
Yes, squash is fine :+1:

**Comment by SuperQ** [comment]
I'm just going to merge this because it's updating upstream commits.

**Pull request merged**
